name: '🚀 publish'

on:
    release:
        types: [created, published]

jobs:
    publish-npm:
        name: 🚀 publish
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2
            - name: 🟢 node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
